---
apiVersion: v1
kind: Service
metadata:
  name: mediamtx
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: rtsp
      {{- if .Values.nodePort.enabled }}
      nodePort: {{ .Values.nodePort.rtspPort }}
      {{- end }}
      port: 8554
      protocol: TCP
      targetPort: 8554
    - name: mmtx1
      port: 1935
      protocol: TCP
      targetPort: 1935
    - name: mmtx2
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: mmtx3
      port: 8889
      protocol: TCP
      targetPort: 8889
    - name: mmtx4
      port: 8890
      protocol: TCP
      targetPort: 8890
  selector:
    app: mediamtx
